### ISSUE TITLE
Error loading JCufft on Windows

### ISSUE THREAD

**Issue by hadim** [jcuda/jcufft#1]
Hello,

JCufft runs without issue under Linux but the .dll don't load on Windows. More interesting is that JCuda main library works.

In short the following code works:

```java
Pointer pointer = new Pointer();
JCuda.cudaMalloc(pointer, 4);
System.out.println("Pointer: "+pointer);
JCuda.cudaFree(pointer);
```

while this one crash : 

```java
float input[] = new float[] { (float) 1.0 };
cufftHandle plan = new cufftHandle();
JCufft.cufftPlan1d(plan, 1, jcuda.jcufft.cufftType.CUFFT_C2C, 1);
JCufft.cufftExecC2C(plan, input, input, JCufft.CUFFT_FORWARD);
JCufft.cufftDestroy(plan);
```

with the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error while loading native library "JCufft-0.8.0-windows-x86_64"
Operating system name: Windows 10
Architecture         : amd64
Architecture bit size: 64
---(start of nested stack traces)---
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no JCufft-0.8.0-windows-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:143)
	at jcuda.jcufft.JCufft.initialize(JCufft.java:89)
	at jcuda.jcufft.JCufft.<clinit>(JCufft.java:73)
	at JCudaTest.main(JCudaTest.java:16)
Stack trace from the attempt to load the library as a resource:
java.lang.UnsatisfiedLinkError: C:\Users\brouhardlab\AppData\Local\Temp\JCufft-0.8.0-windows-x86_64.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:260)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:158)
	at jcuda.jcufft.JCufft.initialize(JCufft.java:89)
	at jcuda.jcufft.JCufft.<clinit>(JCufft.java:73)
	at JCudaTest.main(JCudaTest.java:16)
---(end of nested stack traces)---

	at jcuda.LibUtils.loadLibrary(LibUtils.java:193)
	at jcuda.jcufft.JCufft.initialize(JCufft.java:89)
	at jcuda.jcufft.JCufft.<clinit>(JCufft.java:73)
	at JCudaTest.main(JCudaTest.java:16)
```

I also confirm the file  ` C:\Users\brouhardlab\AppData\Local\Temp\JCufft-0.8.0-windows-x86_64.dll` exists.

Any idea @jcuda ?

**Comment by hadim** [comment]
(note that I am using Cuda 9.0 but the same Cuda 9.0 works without issue under Ubuntu...)

**Comment by jcuda** [comment]
The part 

> Can't find dependent libraries

of the error message indicates that it just cannot find the matching CUFFT DLL, which is

    cufft64_80.dll

I'd offer you to just upload it somewhere or send it via mail. Even better could be to include this DLL in the JARs as well, so that this kind of error can no longer occur at all. But the CUFFT DLL has a whopping **142 MB**, so this is unfortunately not a feasible solution. 

You'll either have to install CUDA 8.0, or (since you mentioned some problems with installing it in the other issue) give the current state of the CUDA 9.0 support a try. 

If you just want to test the functionality (regardless of the (Maven) deployment), I could send you a ZIP with the JARs+DLLs of the current state, which *should* work with CUDA 9.0 locally.

**Comment by hadim** [comment]
I guess the API didn't change a lot between 8.0 and 9.0 because I just copied the `cufft64_90.dll` to `cufft64_80.dll` and it just works.

It's good enough for me at the moment waiting for the 9.0 support.

Would the next version of JCuda support both Cuda 8.0 and 9.0 transparently? So it will work on any machine having one or the other version of Cuda?

For deployment, I think asking the user to install Cuda by himself is not too much to ask. That being said if you know a good maven artifact that ship Cuda I'll take it since it's better for reproducibility.

Last thing, do you think it would be worse catching the exception to give a user like me a more specific message such as:

```
JCuda (or JCufft) wasn't able to find or load the Cuda (or CuFFT) library on your system. Please verify that Cuda 8.0 or 9.0 has been correctly installed and is present in your library path.
// + print the name of the libraries that have been attempting to load.
```
